"""cfo init — onboarding questionnaire.

Writes:
- data/portfolio/profile.md (descriptive)
- data/portfolio/accounts.json (structured)

Refuses to overwrite existing files — user must delete or move first.
"""
import time
from datetime import date, datetime, timezone

import typer
from rich.console import Console

from cfo.core import portfolio as core_p
from cfo.core import profile as core_prof
from cfo.schemas.portfolio import Account, AccountsFile, AccountType, AccountSource
from cfo.util import audit, paths

console = Console()


def _prompt(msg: str, default: str = "") -> str:
    return typer.prompt(msg, default=default, show_default=bool(default))


def _maybe_float(s: str) -> float | None:
    s = s.strip()
    if not s:
        return None
    return float(s)


def _build_profile_md(answers: dict) -> str:
    return f"""# {answers['name']} — Profile

*Generated by `cfo init` on {date.today().isoformat()}*

## Basic
- Age: {answers['age']}
- Occupation: {answers['occupation']}

## Family / Safety Net
- Family backup: {answers['family_backup']}
- Monthly fixed expenses: ${answers['monthly_expenses']}

## Risk / Goals
- Max acceptable drawdown: {answers['max_drawdown']}%
- Investment horizon: {answers['horizon']} years
- Primary goal: {answers['primary_goal']}
- Monthly invest target: ${answers['monthly_invest']}

## Experience
- Paper trading: {answers['paper_done']}
- Options: {answers['options_done']}

## Advisors / Philosophy
- Advisors followed: {answers['advisors']}
- Investing philosophy: {answers['philosophy']}
"""


def _rh_accounts(answers: dict) -> list[Account]:
    if answers["has_rh"].lower() not in {"y", "yes"}:
        return []
    mapping = [
        ("rh-individual", AccountType.taxable, "rh_individual"),
        ("rh-roth", AccountType.roth_ira, "rh_roth"),
        ("rh-traditional", AccountType.traditional_ira, "rh_traditional"),
        ("rh-savings", AccountType.hysa, "rh_savings"),
    ]
    out: list[Account] = []
    for aid, atype, key in mapping:
        raw = answers.get(key, "").strip()
        if raw == "":
            continue
        bal = float(raw)
        out.append(Account(
            id=aid,
            type=atype,
            broker="robinhood",
            source=AccountSource.rh_sync if atype != AccountType.hysa else AccountSource.manual,
            balance=bal,
            last_manual_update=date.today() if atype == AccountType.hysa else None,
        ))
    return out


def _external_accounts(raw: str) -> list[Account]:
    """Parse lines like: chase|checking|12979.47"""
    out: list[Account] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 3:
            continue
        ident, atype_raw, bal_raw = parts
        try:
            atype = AccountType(atype_raw)
        except ValueError:
            atype = AccountType.other
        out.append(Account(
            id=ident,
            type=atype,
            broker=ident,
            source=AccountSource.manual,
            balance=float(bal_raw),
            last_manual_update=date.today(),
        ))
    return out


def init():
    """Interactive onboarding. Writes profile.md + accounts.json."""
    start = time.monotonic()

    if paths.profile_md().exists() or paths.accounts_json().exists():
        console.print(
            "[red]profile.md or accounts.json already exists. "
            "Delete them first if you want to re-init.[/red]"
        )
        audit.record(
            cmd=["cfo", "init"],
            result="error",
            duration_ms=int((time.monotonic() - start) * 1000),
        )
        raise typer.Exit(code=1)

    console.print("[bold]CFO Onboarding — 15 quick questions[/bold]\n")

    answers = {
        "name": _prompt("1. Your name"),
        "age": _prompt("2. Age"),
        "occupation": _prompt("3. Occupation / income"),
        "family_backup": _prompt("4. Family backup? [y/n]"),
        "monthly_expenses": _prompt("5. Monthly fixed expenses (USD)"),
        "has_rh": _prompt("6. Do you have a Robinhood account? [y/n]"),
        "rh_individual": _prompt("   6a. RH Individual balance (blank if none)", default=""),
        "rh_roth": _prompt("   6b. RH Roth IRA balance (blank if none)", default=""),
        "rh_traditional": _prompt("   6c. RH Traditional IRA balance (blank if none)", default=""),
        "rh_savings": _prompt("   6d. RH Savings (HYSA) balance (blank if none)", default=""),
        "external": _prompt(
            "7. External accounts (one per line, format: id|type|balance)\n"
            "   types: taxable/roth_ira/traditional_ira/checking/savings/hysa/other\n"
            "   (empty line to finish)",
            default="",
        ),
        "max_drawdown": _prompt("8. Max acceptable drawdown %"),
        "horizon": _prompt("9. Investment horizon (years)"),
        "primary_goal": _prompt("10. Primary goal [retirement/house/tuition/FI/other]"),
        "monthly_invest": _prompt("11. Monthly invest target USD"),
        "paper_done": _prompt("12. Paper traded before? [y/n]"),
        "options_done": _prompt("13. Used options before? [y/n]"),
        "advisors": _prompt(
            "14. Advisors / YouTubers to follow (comma-separated, empty ok)", default=""
        ),
        "philosophy": _prompt("15. One-line investing philosophy"),
    }

    # Profile.md
    core_prof.save(_build_profile_md(answers))

    # Accounts
    accounts = _rh_accounts(answers) + _external_accounts(answers["external"])
    af = AccountsFile(
        schema_version=1,
        last_updated=datetime.now(timezone.utc),
        accounts=accounts,
    )
    core_p.save(af)

    console.print(f"\n[green]ok[/green] profile.md written to {paths.profile_md()}")
    console.print(f"[green]ok[/green] accounts.json written to {paths.accounts_json()}")
    console.print(f"[green]ok[/green] {len(accounts)} account(s) recorded")

    audit.record(
        cmd=["cfo", "init"],
        result="ok",
        duration_ms=int((time.monotonic() - start) * 1000),
    )
